version: '3.3'
services:

  frontend:
    container_name: foodgram-front
    image: hikkiadvent/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/
    networks:
      - foodgram-network

  db:
    container_name: foodgram-db
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    networks:
      - foodgram-network

  backend:
    container_name: foodgram-app
    image: hikkiadvent/foodgram_backend
    restart: always
    volumes:
      - static_dir:/backend_static/static/ 
      - media_dir:/app/media/
    env_file:
      - ../.env
    networks:
      - foodgram-network

  nginx:
    container_name: foodgram-proxy
    image: hikkiadvent/foodgram_gateway
    restart: always
    ports:
      - 8500:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_dir:/etc/nginx/html/static/
      - media_dir:/etc/nginx/html/media/
    depends_on:
      - backend
      - frontend
    networks:
      - foodgram-network

volumes:
  static_dir:
  media_dir:
  postgres_data:

networks:
  foodgram-network:
    driver: bridge
