# Generated by Django 4.2.17 on 2024-12-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_options_alter_recipeingredient_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=2, upload_to='image/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
