# Generated by Django 4.2.17 on 2024-12-26 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_subscription_followed_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(through='users.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
