# Generated by Django 4.2.17 on 2024-12-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_subscriptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Follower',
        ),
    ]
