# Generated by Django 3.2.16 on 2025-01-26 10:45

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20250120_1329'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_user_recipe_shopping_cart',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'blank': 'Это поле обязательно для заполнения.', 'unique': 'Пользователь с таким юзернеймом уже существует.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Введите корректный юзернейм. Разрешены буквы, цифры и символы: @ . + - _', regex='^[\\w.@+-]+$'), users.validators.me_validator], verbose_name='Имя пользователя'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_recipe_shoppingcart'),
        ),
    ]
