# Generated by Django 4.2.17 on 2024-12-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_favorite_options_alter_favorite_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='measurement_unit',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Единица измерения'),
        ),
    ]
