# Generated by Django 4.2.17 on 2025-01-07 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_quantity_recipeingredient_amount_and_more'),
        ('users', '0009_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppinglist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='recipes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='recipes.recipe', verbose_name='рецепты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='shopping_list',
            field=models.ManyToManyField(related_name='users', through='users.ShoppingList', to='recipes.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppinglist',
            unique_together={('user', 'recipes')},
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='measurement_unit',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='quantity',
        ),
    ]
